extends:
  - macklinu
  - macklinu/react

rules:
  func-style:
    - error
    - expression
    - allowArrowFunctions: true
  no-use-before-define: error
  arrow-body-style:
    - error
    - as-needed
