extends:
  - macklinu
  - macklinu/react

plugins:
  - import
  - simple-import-sort

rules:
  func-style:
    - error
    - expression
    - allowArrowFunctions: true
  no-use-before-define: error
  arrow-body-style:
    - error
    - as-needed
  import/exports-last: error
  import/default: error
  import/group-exports: error
  import/no-anonymous-default-export: error
  import/no-duplicates: error
  import/order: off
  simple-import-sort/sort: error
